### ISSUE TITLE
[ClangFormat] Add CaseSensitive to rule for Qt

### ISSUE THREAD

**Issue by SunBlack** [PointCloudLibrary/pcl#5212]
Currently the `.clang-format` file contains

```yml
IncludeCategories:
...
# Major 3rd-Party components of apps
  - Regex:           '^<Q[^/]+>$'
    Priority:        300
...
# Matches all std includes. Match them before any unknown include, so we can order them behind.
  - Regex:           '^<[a-z_]+>$'
    Priority:        900
```

Sadly the std include `<queue>` will be matched by the first rule, as the regular expressions [are not case sensitive](https://reviews.llvm.org/D91507#change-rGLQV0mPnmFt). This issue can be simply resolved by adding `CaseSensitive: true` to the rule for Qt - but this requires at least ClangFormat 12 (as far as I see the CI is currently using ClangFormat 10 of Ubuntu 20.04). Another option would be to adjust the regular expression, but as 22.04 will be released in a few weeks in may be easier to upgrade to 22.04 and use ClangFormat 14.0 than.
